# Generated by Django 2.1.5 on 2019-01-20 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=150)),
                ('organization_logo', models.ImageField(upload_to='logo')),
                ('title', models.CharField(default='New Event', max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True)),
                ('venue', models.TextField()),
                ('link', models.URLField()),
                ('price', models.PositiveIntegerField(blank=True)),
                ('event_image_1', models.ImageField(upload_to='event_images')),
                ('event_image_2', models.ImageField(blank=True, upload_to='event_images')),
                ('event_image_3', models.ImageField(blank=True, upload_to='event_images')),
                ('event_image_4', models.ImageField(blank=True, upload_to='event_images')),
                ('contact_no', models.BigIntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
