# Generated by Django 2.1.5 on 2019-01-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190120_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
