# Generated by Django 2.1.5 on 2019-01-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190120_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_4',
            field=models.ImageField(blank=True, default='null', upload_to='event_images'),
        ),
    ]
