# Generated by Django 2.1.5 on 2019-01-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190120_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
